rm: cannot remove 'output/*': No such file or directory
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
Traceback (most recent call last):
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/bin/parallel-manipulator", line 5, in <module>
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
    from connectome_manipulator.cli_parallel import app
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 76, in <module>
    setup()
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/connectome_manipulator/cli_parallel.py", line 53, in setup
    is_client = initialize(
  File "/gpfs/bbp.cscs.ch/project/proj112/home/kurban/christoph_paper/github/venv_3_10_8/lib/python3.10/site-packages/dask_mpi/core.py", line 75, in initialize
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
srun: error: r1i6n28: task 6: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=2206500.0
slurmstepd: error: *** STEP 2206500.0 ON r1i6n19 CANCELLED AT 2024-05-27T17:05:53 ***
srun: error: r1i6n24: task 4: Exited with exit code 1
srun: error: r1i6n22: task 3: Exited with exit code 1
srun: error: r1i6n25: task 5: Exited with exit code 1
srun: error: r1i6n21: task 2: Exited with exit code 1
srun: error: r1i6n19: task 0: Exited with exit code 1
srun: error: r1i7n30: task 9: Terminated
srun: error: r1i7n29: task 8: Terminated
srun: error: r1i6n29: task 7: Terminated
srun: error: r1i6n20: task 1: Terminated
srun: Force Terminated StepId=2206500.0
